AllCops:
  RunRailsCops: true
  Exclude:
    - spec/dummy/db/schema.rb
    - Gemfile
    - Rakefile
    - 'public/clew/*'

StringLiterals:
  EnforcedStyle: single_quotes
  Enabled: true

LineLength:
  Description: 'Extend line length to 120 characters.'
  Enabled: true
  Max: 120