sqlite: &sqlite
  adapter: sqlite3
  database: db/<%= Rails.env %>.sqlite3

mysql: &mysql
  adapter: mysql2
  username: <%= ENV['DB_USERNAME'] || "root" %>
  password: <%= ENV['DB_PASSWORD'] || "" %>
  database: air_ci_<%= Rails.env %>

postgresql: &postgresql
  adapter: postgresql
  username: <%= ENV['DB_USERNAME'] || "postgres" %>
  password: <%= ENV['DB_PASSWORD'] || "" %>
  database: air_ci_<%= Rails.env %>
  min_messages: ERROR

defaults: &defaults
  pool: 5
  timeout: 5000
  host: localhost
  <<: *<%= ENV['DB'] || "mysql" %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults